# Generated by Django 5.1.2 on 2025-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarees',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
