# Generated by Django 5.1.2 on 2025-08-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_sarees_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarees',
            name='price',
            field=models.IntegerField(),
        ),
    ]
